enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
comforts = true
farmersdelight = true
supplementaries = true
chipped = true
betternether = true
milk = true
create = true
decorative_blocks = true
handcrafted = true
universal_graves = true
betterend = true
rechiseledcreate = true
carpeted = true
minecraft = true
rechiseled = true
gravestones = true
